######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 26 15:02:57 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += http_request.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
